#pragma config(Sensor, S2,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool tvalue = SensorValue[S2];
	motor[motorB] = 50;
	motor[motorC] = 50;
	while (tvalue == false) {
		tvalue = SensorValue[S2];
		delay(50);
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
}
