#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn(char* direction) {
	if (direction == "r") {
		motor[motorB] = -50;
		motor[motorC] = 50;
		delay(636);
	}
	else if (direction == "l") {
		motor[motorB] = 50;
		motor[motorC] = -50;
		delay(636);
	}
}

task main() {
	while (true) {
		while (SensorValue[S1]==false) {
		motor[motorB] = 100;
		motor[motorC] = 100;
		}
		turn("r");
	}
}
