#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void da(char* dirorstraight, int l, int s, bool ua) //Do Action Specified
{
	if (dirorstraight	== "f") { // If it wants to go straight
		motor(motorB) = s;
		motor(motorC) = s;
	}
	else if (dirorstraight == "l") { // If it wants turn left
		motor(motorB) = s;
		motor(motorC) = -s;
	}
	else if (dirorstraight == "r") { // If it wants turn right
		motor(motorB) = -s;
		motor(motorC) = s;
	}
	else if (dirorstraight == "b") { // If it wants go backwards
		motor(motorB) = -s;
		motor(motorC) = -s;
	}

	if (ua == true) { // If i specify to change duration to the angle to turn at, then
		delay((14.08 * (((s-50)*-1)+50)/100)*l); // Angle Script
	}

	else if (ua == false) { // If I dont specify to convert duration to angle
		delay(l); // Wait duration
	}
	motor(motorB) = 0;
	motor(motorC) = 0;
}

int lightval;

void move() {
	motor[motorB] = 50;
	motor[motorC] = 50;
	delay(10);
}
	
void action() {
		lightval = SensorValue[S3];
		if (lightval > 35) {
			motor[motorB] = -50;
			motor[motorC] = 50;
			delay(10);
		}
		else {
			motor[motorB] = 50;
			motor[motorC] = -50;
			delay(10);
		}
		move();
}


task main()
{
	while (SensorValue[S1] == false){
		da("f",10,50,false);
	}
	da("b",500,50,false);
	da("l",140,25,true);
	da("f",1700,50,false);
	int i;
	
	for (i=0;i<650;i++){
		
		action();
	
	}
	
	while (SensorValue[S4] > 5){
		da("f",10,50,false);
	}
	da("r",90,50,true);
	da("f",1500,50,false);
	da("r",90,50,true);
	da("f",1000,50,false);
	da("l",90,50,true);
	while (SensorValue[S4] < 1){
		
	}
	da("r",85,50,true);
	da("f",7000,50,false);
}
